language: go

notifications:
  email:
    on_success: never
    on_failure: always

go:
  - "1.14.x"

env:
  global:
    - GO111MODULE=on
    - DEBUG=true
    - CODECOV_TOKEN="a3700b77-876b-4923-909b-3ee2b2871be0"

install:
  - go mod download

script:
  - make ci-test

after_success:
  - bash <(curl -s https://codecov.io/bash)
