language: go

notifications:
  email:
    on_success: never
    on_failure: always

go:
  - "1.14.x"

env:
  global:
    - GO111MODULE=on
    - DEBUG=true
    - CODECOV_TOKEN="5a7376b5-38ad-4255-9fb0-2e9ca4fb23c7"

install:
  - go mod download

script:
  - make ci-test

after_success:
  - bash <(curl -s https://codecov.io/bash)
